### ISSUE TITLE
Revisit fmtPercent multiplier

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1274]
We made a change in #1192 to multiple values passed to fmtPercent by 100, primarily driven by the Excel export use-case.

A new complication with this breaking change has emerged in the form of ag-grid value filters. Those work (of course) off of the underlying value, so a user ends up seeing a column with cell values such as 20% but would need to enter .2 in a value filter to target. 

Unwind the change and fix / multiple in the export code if possible?
Provide a flag on the formatter to control the behavior and decide on the default?

**Comment by amcclain** [comment]
@johnbc has noticed this also affects cell copying

**Comment by haynesjm42** [comment]
Yes cell copying will always take the raw un-formatted value that we are providing to the grid. I think this is correct behavior, if you copy a percent cell in our grid and paste into an excel column which is formatted as a percentage, it works as expected.

For the ag-grid value filter issue, I believe that is the purpose of the `filterValueGetter` callback on column defs. If you are using a renderer on a filterable column, then you probably also want a `filterValueGetter` which returns the same formatted value as the renderer - should we install this by default? I would imagine StoreFilterField has the same issue since it works off of the Record field values?

**Comment by amcclain** [comment]
Closing ticket:
- Agree that copying 20% as 0.2 is arguably most correct
- Devs using agGrid col filters can also install an appropriate filterValueGetter as per above
