### ISSUE TITLE
Number Input precision should flow through to commited value

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1305]
Currently, the precision appears to only be a matter of the rendered value, while the underlying model retains the lossless val:

![Screen Shot 2019-08-09 at 12 55 53 PM](https://user-images.githubusercontent.com/15745614/62795762-78c41f80-baa5-11e9-859e-103aeaad1681.png)

**Comment by febbraiod** [comment]
Client app with multiple inline grid editors is working around this, would love a heads up if this were to be resolved.

**Comment by cnrudd** [comment]
If this were implemented, how should this scenario play out:
* data with numbers to 9 decimal places fills a form with numberInputs with precision set to 4.
* Is the form automatically dirty because numbers with more than 4 decimal precision were changed to 4?
* user changes some numbers but not all, then saves form.
* Do all numbers get pulled from the form with precision 4 now?

If we implement "precision flows through to committed value", we might want a way to turn off precision.  It appears the only way to do that would be to set precision to a high value like 15.

Or would be better to make this new feature optional with a prop:  maintainPrecision   enforcePrecision etc..?

**Comment by cnrudd** [comment]
Above is a commit in a new branch.  This first commit is a simple implementation of the "flow through" idea without any flags.  Maybe easier to reason about, test the other questions now.

**Comment by pauldelano** [comment]
FWIW, I have an application where they desire the ability to display to 4 places and edit/save to 6 places.

**Comment by cnrudd** [comment]
@paul  display to 4 in a grid cell?  And when edited the inline cell editor
shows 6?
Or a real form in which they want this?

Colin

**Comment by lbwexler** [comment]
Paul -- trying to get my head around that use case -- seems really strange to me on a form.   Am I missing something, or do others agree that this is very counter-intuitive for numberInput itself.

Grid rendering vs. editing is potentially a different thing I guess, but not really related to this ticket

**Comment by pauldelano** [comment]
The specific request was for a form, not grid editing. Seems like it's the same issue in any case. Currently NumberInput shows the requested number precision when it is displayed and arbitrary precision when it has focus.

I would think that ultimately it would be helpful to limit the edit precision separate from the display precision since in some cases you want to display the rounded-up value and in other cases you want to limit the entry. Like for 2 places for $USD.

I asked the user for exactly what they want and will relay details when I have them.

**Comment by amcclain** [comment]
Arg, just ran into this issue with a form containing a numberInput that should only accept ints. The current behavior is undeniably surprising / confusing.

I believe that I follow the advanced use case of maintaining different precisions for a single field, but it does seem rather exotic to me. Seems to create the potential for mistakes, with a user scanning over a form and thinking that they are looking at the exact values specified, when in fact they are not.

I could also imagine it being confusing if you have a `maxPrecision:1` + a constraint like `numberIs({max: 1})` and an actual value of `1.1` - control shows both `1` and a validation error:

<img width="479" alt="Screen Shot 2021-05-17 at 11 15 06 AM" src="https://user-images.githubusercontent.com/225806/118536951-33646580-b701-11eb-8597-b7bd85bc7689.png">

@pauldelano checking to see if this is still a current requirement in the app?

Either way, would be good to unblock here so we can improve the story around this currently quite confusing prop.
