### ISSUE TITLE
Null values in grid are not grouped

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#1357]
Rows that have a null value for a grouped column are placed at the end of the grid and are not in any group. They should be grouped in a null group.

**Comment by lbwexler** [comment]
John -- Can you take a look a this?  Please reach out to paul for more details -- think it was reproducible in toolbox

**Comment by amcclain** [comment]
My sense was that this is simply the ag-Grid default behavior and not a bug per se. I agree that I do find it confusing.

Do we think it would be better to print something like "[null]" in the grouped header by default?  I suppose that would be better / less surprising in terms of keeping the overall shape more consistent (i.e. everything in a group). 

Maybe a more user-friendly string like "None" or "No {columnHeader}"?  Make it configurable (but at what level)?

**Comment by haynesjm42** [comment]
This is indeed just the way that ag-grid handles null/undefined values in grouping columns: https://www.ag-grid.com/javascript-grid-grouping/#unbalanced-groups

The way I have dealt with this in apps is via `processRawData`, have not had a case where it was not acceptable for me to just mutate the records. If you can't just replace the nil values on the records because of other app logic depending on those nil values, you would need to use a `valueGetter` on the columns to give ag-grid something it can group on.

We could support a new Column config (`emptyValue`? could be a static value or a function) and install a `valueGetter` which would return that if the actual column value is null/undefined/empty string. In simple use-cases the app can just add that to the `colDefaults` config on the GridModel. 

There are caveats to that approach, as I don't believe there is a way for us to have that value only be used for grouping purposes. If the column is visible then those "empty" values would appear in the grid, and those values would be passed to renderers and anything else which uses the column value. We could potentially handle this for renderers by passing the value of the actual record field instead of what ag-grid passes in the cell renderer callback, but that seems overly complicated and likely to cause bugs/confusion.

Also if the app installed their own `valueGetter` on the column it would blow ours away of course, not sure how often apps use `valueGetter` through the `agOptions` (hopefully not often) but seems like one of the more likely `agOptions` to be used by apps.

**Comment by lbwexler** [comment]
In discussing with paul, I understood that this was a regression.  Is this *not* the case?  Paul can you comment? 

Assuming not in fact a regression on our side, does the workaround to install a non-null value work?

**Comment by pauldelano** [comment]
I tried regressing back a few versions and could not find a case where it grouped by nulls. So, no, I don't think the behavior has changed.

I noticed that not grouping by nulls is inconsistent with how agGrid grouped filters work. Grouped filters show both nulls and empty strings as a (Blanks) category that can be selected. So if I have records with empty strings and nulls and then filter on (Blanks) I see a group of empty string records with a count of X but then see a bunch more null records that are shown as empty cells but aren't included in the X count.

For my project it is acceptable to replace null values with empty strings in processRawData. It will require some extra checking for inline edited values in addition to the processRawData changes. There is also a bit of a hazard when replacing numeric column null values with string types since it's not acceptable to replace with 0 or NaN.

My ultimate preference is to have the grid group all blank types into one Blank group. Note that empty string groups display with just the count and no label, so seeing "Blank (42)" instead of "(42)" is desirable.

**Comment by febbraiod** [comment]
Think I have a solution that addresses John's concern that we can't get the column to use a special value only for grouping. Not sure I can do anything about a custom value getter blowing ours away, but standby...

**Comment by lbwexler** [comment]
Thanks for the hard work here Don.

I am going to agree with John's Assesment here -- I think the risk is that the cure here is worse than the disease. It complicates a pretty complicated story already. Let's let apps deal with this by pre-processing their nulls, either before presenting to the grid, or before loading the store its data.
