### ISSUE TITLE
Grouped Grids Don't Export in Hierarchical form in Excel

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1372]
Malvina noticed that our ag- grouped grids don't export with the native excel tree format that is done with our tree grids. Is this a possibility.

We should feel free to close if this seems like it would be very difficult.

**Comment by TomTirapani** [comment]
Got round to taking a look at this.

Currently, hierarchy is interpreted on the backend through changes to a `depth` value as we iterate through a list of records. This means that each group must by followed by at least one record at a higher depth, in order to close the group. With our tree grid this works, because each group is followed by one or more records at the root depth, but with ag-grid groups this isn't the case. Thus a list of groups is interpreted as one group.

One way to potentially fix this would be to group by a key rather than a depth property. However, this would require changes to both front and backend, so wanted to check if we think the change is justified. unfortunately, since the groups don't have a 'root' record in the store, we would have to adjust the client-side and backend apis to support groups based
