### ISSUE TITLE
App goes into an infinite loop if itemHeight is not specified for DataView component

### ISSUE THREAD

**Issue by nadkarniarjun** [xh/hoist-react#1436]
It seems that agGrid goes into an infinite loop trying to calculate the row height of each of the elements.

**Comment by lbwexler** [comment]
Really on the fence about whether to use a default of, say 25px, or make this required.
Could go either way.

**Comment by amcclain** [comment]
I would vote for making it required - otherwise I could imagine developers wasting time thinking that there was some layout prop, style, or CSS property they needed to set on their components to get the view to be rendering them correctly. 

I also doubt there is any default pixel value we would could choose that developers would keep in place, other than by coincidence, so the default doesn't seem like it would ever be applied in practice.  

We should add the missing prop-type definitions for `itemHeight` (with the required qualifier) as well as `rowCls` and `onRowDoubleClicked`. The prop-types are for dev-time warnings only though, so given how bad the bug is we should probably also throw within render....

**Comment by lbwexler** [comment]
Great -- lets make it required then -- agree.  

I think the dev time check is probably enough, but a throwIf() can't hurt.

-Lee

**Comment by nadkarniarjun** [comment]
Agreed that it should be a required param. Just submitted a PR into develop for this bug.

**Comment by lbwexler** [comment]
reviewing this now with arjun
