### ISSUE TITLE
Exported data in TreeGrid does not match data displayed in browser

### ISSUE THREAD

**Issue by mpeckerman** [xh/hoist-react#1447]
To reproduce:

1. Navigate to Toolbox -> Grids -> Tree (or Tree w/Checkbox or Grouped Columns) screen
2. Apply a filter that excludes some of the records.
3. Click "Export" icon
4. Open file
5. Review aggregated data. The aggregates in the Excel file will not match the browser.
![Screen Shot 2019-11-12 at 3 01 51 PM (3)](https://user-images.githubusercontent.com/40367298/68709344-820cce80-0563-11ea-86b8-446385a7e94b.png)
<img width="1440" alt="Screen Shot 2019-11-12 at 3 04 07 PM" src="https://user-images.githubusercontent.com/40367298/68709363-8df89080-0563-11ea-86de-0850f4cd43a4.png">

**Comment by mpeckerman** [comment]
Navigate to Toolbox -> Grids -> Tree (or Tree w/Checkbox) screen

**Comment by mpeckerman** [comment]
Navigate to Toolbox -> Grids -> Tree (or Tree w/Checkbox) screen

**Comment by lbwexler** [comment]
Peter -- can see if you can reproduce this?  Want to take advantage of your deep love of excel.

**Comment by peterjcoffman** [comment]
I can reproduce this. It occurs if you follow the steps described in the issue _with a filter enabled._

**Comment by peterjcoffman** [comment]
Found an additional problem: the exported values are not formatted the same as the values displayed in the browser. For instance, the TreeGrid example for this issue formats market value as millions of dollars, and the header states that the units are millions. However, when exported, the data is not formatted as millions.

Maybe we don't want to format data when exported since that throws out some data. In that case, the headerName of the exported data inaccurate.

**Comment by peterjcoffman** [comment]
PR is here:
https://github.com/xh/hoist-react/pull/1488

This was actually somewhat worse than I thought. I do not know where the data we were previously using came from and it didn't work properly. For instance, it does not reflect the configured aggFunc: if the aggFunc is max, the exported version would still be a sum.

**Comment by peterjcoffman** [comment]
The aggregation data that was being exported before came straight form the PositionService, which calculates the aggregates server-side.

**Comment by lbwexler** [comment]
Great fix 👍 

Thanks!
