### ISSUE TITLE
Select input performance issues with large option lists

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1458]
The performance of the Select input component becomes very poor with large option lists. Both opening the list itself when clicking on the select, and attempting to navigate the list when open, become very unresponsive. 

Have not done extensive testing to see how many options it can handle before the performance issues become noticeable, but it does perform very badly with ~2500 options.

It looks like this is an issue in general with react-select, and recommended solutions are to provide a custom Menu component and truncate the list of options being rendered (forcing user to type in text to filter the list). Also other optimizations such as providing a custom option component to remove mouse event handlers (and some other things) to speed up user interaction on the option list itself might be useful/sufficient.

Relevant react-select issue with several proposed solutions: https://github.com/JedWatson/react-select/issues/3128

**Comment by amcclain** [comment]
Thanks for filing - this was one of the lingering issues left in #733 but deserves its own ticket so we can get more visibility on it.

IIRC this was the one real regression we had in behavior over the prior Blueprint implementation, where I believe we had some solution in place for a brief period of time before it became clear we wanted to jump to another component for a variety of other reasons.

I think it's reasonable to assume (as a general principle) that a 1000+ option dropdown would be minimally useful (without typing to filter) even if performance wasn't a problem. That points to an approach that would truncate the list automatically at a preset limit, potentially inserting a final (unselectable) option such as "Not all options displayed, enter text to filter..." so it was clear to the user who did scroll to the bottom of the list that they were not seeing everything. 

This would of course require `enableFilter: true`. Otherwise we might need to resort to just printing a dev-time console warning or similar... 

But there are a lot of pointers on that busy issue, including some like the above.....

**Comment by haynesjm42** [comment]
I wonder if we would get acceptable performance by replacing the menu component with one that uses a Grid/DataView to take advantage of ag-Grid row virtualization. For basic lists which just show the label, using a standard Grid component should result in great performance. In the case that the option element is customized, we'd need to use a DataView, which would potentially have performance issues on scroll while the grid is destroying/creating react components, but I bet it would still perform much better than the default menu in react-select

**Comment by haynesjm42** [comment]
I have a select with about 330 options in it where the mouse hover and scrolling delays are very noticeable (though not nearly as bad as it is with ~2000 options). Pretty disappointing that the out-of-the-box performance of react-select can't handle a few hundred options..

**Comment by peterjcoffman** [comment]
I found a library that aims to improve performance. Maybe we don't want to pull in another dependency, but it's interesting.

https://github.com/guiyep/react-select-virtualized

I've tested it and it does dramatically improve the performance of creating and scrolling a large Select. It is perfectly usable with 10,000 elements. I couldn't get it to work with filtering (which is obviously important), but I also didn't try that hard.

**Comment by haynesjm42** [comment]
Thanks for looking into it @peterjcoffman - that lib looks very promising! If I am understanding correctly it should just be a drop-in replacement for our the react-select components we are using?

This comment in their readme was somewhat concerning: 

> We do not support any related prop to the popup list. We extend it. *Sorry no extension of any component inside the list.*

Does this mean our option list item renderer wouldn't work?

**Comment by lbwexler** [comment]
Peter -- thanks for taking a look -- assigning you.

**Comment by peterjcoffman** [comment]
I have this set up using this library:

https://github.com/jacobworrel/react-windowed-select

This is _not_ the react-select-virtualized library I was looking at before. It is based on react-window, which is the successor to react-virtualized.

The performance is much improved. It is, unfortunately, not perfect. Opening the select is slow, as is mousing over elements, filtering, or selecting elements.

**Comment by peterjcoffman** [comment]
PR is here:
https://github.com/xh/hoist-react/pull/1502
I think we should test this very thoroughly before changing such an important dependency.
