### ISSUE TITLE
Slider breaks badly when labelStepSize is zero

### ISSUE THREAD

**Issue by peterjcoffman** [xh/hoist-react#1464]
When the labelStepSize on a slider is set to zero, the app hangs and memory usage steadily increases until the tab crashes.

I believe this is because it goes into an infinite loop of adding labels.

**Comment by lbwexler** [comment]
I suspect we will find a number of things now that we have the easy ability to more easily poke our components in crazy ways.  We don't expect to have developers do this, but the result is so bad, that its worth protecting against.

Can we quietly enforce a sensible min here? These can presumably be decimal value so that might be tricky?  Other options is just a throwIf() or a warnIf() and

**Comment by peterjcoffman** [comment]
PR is here:
https://github.com/xh/hoist-react/compare/sliderLabelStepSizeFix?expand=1
