### ISSUE TITLE
TabContainerModel should be a RefreshContextModel

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1477]
I think it used to be? Or at least you could call `refresh` or similar on it, but right now there is no way to programatically trigger a refresh on the active tab (and mark other tabs as refresh pending) without adding a model/component to wrap the tab container.

**Comment by lbwexler** [comment]
@haynesjm42 -- I can see how this could theoretically be useful, but then you could argue we should be making DockContainerModel and also DashContainerModel.  

What is the use-case when you want to only refresh the container component, and not everything else in the RCM that contains it? 

If we can get a common use case, lets do this, I would say otherwise let's encourage application to use the underused RefreshContextView wrapper for the purpose you describe. 

Also note that we have a related ticket to make PanelModel potentially be an RCM to allow lazy refresh of its contents.  If we did that, it will be that much more likely that you already have a targeted RCM near by or available from context to do what you need.

**Comment by lbwexler** [comment]
Discussed with John, and we are going with the argument I outlined above.  He used a RefreshContextView effectively where needed in the dash.
