### ISSUE TITLE
Placeholder text color for select does not match other input components in dark mode

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1516]
It is a brighter white/gray than what appears in text inputs, pretty noticeable when they are stacked on top of eachother, we should fix the css to make sure we are using the exact same color (and add a css var for placeholder text if we don't already have one)

I'm pretty sure it matches in light mode, but not in dark mode. Did not inspect the elements to confirm, but looks closer in light mode.

**Comment by TomTirapani** [comment]
Our placeholder style was being overriden by Blueprint in dark theme. Moving our style to a more specific selector fixed it. Also went with using the `::placeholder` syntax rather than `::-webkit-input-placeholder`... we are using the PostCSS autoprefixer to add those vendor prefixes for us.

I did an audit of all our inputs in desktop and mobile and confirmed the placeholder var (and font-weights, etc) are consistent.

PR: https://github.com/xh/hoist-react/pull/1561
