### ISSUE TITLE
Add CodeInput

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1551]
This would be a HoistInput with a managed codemirror instance.  Like our current JsonInput but without the hard-coded expectation that you are editing JSON.

Should make it easy to customize codemirror / access the full codemirror API.

Could then review JsonInput to see if it becomes a wrapper around this new proposed comp.  Sounds like a good idea, but might be reasons to keep them distinct.

**Comment by peterjcoffman** [comment]
This is pretty straightforward, except I think it will require using dynamic imports. CodeMirror supports languages as modes.

https://codemirror.net/mode/

Each of these modes lives in its own JavaScript file. To avoid importing all of them, we will probably want to have the developer specify which mode to import.

I can get this to work just fine if I import the mode at the top of the file, but if I try to do so dynamically it doesn't work properly.

See this PR:
https://github.com/xh/hoist-react/pull/1553
It does not work properly. But if you move the ```        import('codemirror/mode/apl/apl');``` from line 99 to line 33, then the JsonInput works just fine as an AplInput.

**Comment by peterjcoffman** [comment]
I believe the existing JsonInput is broken. The linting seems to do nothing at all, at least in the examples I can find in Toolbox.

**Comment by peterjcoffman** [comment]
So the lint does work. But it has two differences from what I expected:

1. It does not point out all problems. If you type `{"hi"`, that will be flagged as an error. But if you type `asdfgioniuto`, that will not be flagged.

2. It does not put a marker in the gutter.

My current implementation seems to flag more errors and puts a marker in the gutter. So that is a different behavior.
