### ISSUE TITLE
ButtonGroupInput gets into a bad state: Multiple depressed buttons.

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1592]
From a Client report

> We found a bug in the buttonGroupInput component. It happens when you select one of the items of the group and then press Tab + Enter at the exact same time. The result is that the selection moves to the next button of the group but the previous one also remains selected (and the first item now becomes impossible to de select). We are using Hoist 28 but the bug is replicable on the Toolbox website as well.

**Comment by peterjcoffman** [comment]
Here is an example:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/48924151/73027783-0f8d5a00-3e02-11ea-9cba-c8e0f26ce475.png">

All three buttons are depressed.

This seems to be visual. The button group still works, but the buttons are all displayed as depressed.

**Comment by amcclain** [comment]
Sounds like some kind of mood elevator is required.... 😓😓😓

**Comment by peterjcoffman** [comment]
This is reproducible on the base Blueprint component. Take a look at the second example on [this page](https://blueprintjs.com/docs/#core/components/button-group). You can get it into the same bad state as our ButtonGroup.

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/48924151/73392237-62a25980-42a7-11ea-9843-d6df6e7ff38d.png">

**Comment by lbwexler** [comment]
Hi Peter -- Can we workaround this?  

If not, can we file a ticket with blueprint that we can reference.  Would like to have that in hand so we can get back to our client.

**Comment by peterjcoffman** [comment]
>Hi Peter -- Can we workaround this?

I don't know. Maybe I can figure something out.

>If not, can we file a ticket with blueprint that we can reference. Would like to have that in hand so we can get back to our client.

We should probably file a ticket regardless. It is a blueprint bug.

**Comment by lbwexler** [comment]
Would like to close this one out with some resolution as it came from a customer .

Can we file it here if needed?  https://github.com/palantir/blueprint

**Comment by peterjcoffman** [comment]
@lbwexler I haven't made any progress on a workaround. The component form Blueprint doesn't expose a whole lot for me to work with. So I think filing a ticket with them is the next step.

**Comment by lbwexler** [comment]
great please do so asap

**Comment by peterjcoffman** [comment]
@lbwexler 

I have filed a ticket with Blueprint.

**Comment by peterjcoffman** [comment]
The issue is that we keep track of whether or not a button is pressed in two ways:

1. The parent ButtonGroupInput's `renderValue` === the buttons `value`. This is the only way we want to use.
2. The child Button's internal `isActive` state, which is managed [in this file](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/button/abstractButton.tsx). This causes keypresses to have some extra effects on the state that are not desirable in our use case.

If _either_ of those is true, then the button is shown as pressed. But the state of the button is handled internally by Blueprint, and I don't see a good way to get at it.
