### ISSUE TITLE
Enhancement to "autosize columns" functionality

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1736]
+ Need to clarify/simplify best practices for doing this programmatically.  Specifically, when is agGrid ready, after being presented with new data?  How to deal with data in virtualized rows?

+ Need an affordance to allow users to do this on mobile.  Specifically, we discussed:
  - double-tap on header to resize individual column. 
  - button or option on column chooser to resize columns.

**Comment by amcclain** [comment]
@cnrudd also reports that the following CSS override improves the reliability of autosizing in some client apps, specifically that it helps ensure fewer values remain truncated:

```
.with-autosize-columns {
    .xh-ag-grid {
        .ag-row {
            .ag-cell {
                overflow: unset;
                .ag-cell-wrapper {
                    .ag-group-value {
                        overflow: unset;
                    }
                }
            }
        }
    }
}
```

He suggested investigating with ag-grid to see if this points to a bug or similar there.

**Comment by TomTirapani** [comment]
Taking a look at the mobile affordances for this.

The double tap / click on header works well, and I think would be a clear win for both mobile and desktop.

Adding a button the mobile column chooser isn't quite as good - it seems that in practice, due to a combination of small screens and column virtualisation, it doesn't actually have much of an effect. Newly added columns are likely to be off-screen, and I think maybe adding the affordance would be a case of over-promising. Perhaps best to just require the user to double-tap the columns they want to resize, where it is guaranteed they won't be virtualised?

**Comment by TomTirapani** [comment]
Of course, if we could find someway to make it work for virtualised columns / rows, then that's a different story :)

**Comment by lbwexler** [comment]
Seems like adding this affordance would be a clear quick win.  Great idea
Tom.

-Lee

**Comment by TomTirapani** [comment]
Opened this PR: https://github.com/xh/hoist-react/pull/1757 for the column header double-click functionality

**Comment by lbwexler** [comment]
@TomTirapani - know we have added the double tab affordance here, and also just recently added a button affordance as discussed throughout a client app.

Would it be useful to add a "drop-in" button to the framework -- ala ColumnChooserButton.

**Comment by TomTirapani** [comment]
Sure thing, seems like an easy win - pr here: https://github.com/xh/hoist-react/pull/1863

**Comment by lbwexler** [comment]
Thanks Tom -- Think we fully addressed this ticket for now!
