### ISSUE TITLE
GridModel.autoSizeColumns() should not run if grid cannot be sized

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1747]
The ag-Grid autosize routine can go badly wrong if it can't render and measure column widths - this has been reported as happening when the app is in a background tab and e.g. a timed refresh that calls autoSizeColumns() runs.

Look to see if we can defend against calls to `GridModel.autoSizeColumns()` that we are confident will fail - @cnrudd has found that `agApi.gridCore.eGridDiv.clientWidth > 0` can be used. We could also look to install and measure a ref on the overall grid, and consider if we have any other tools we can use to detect cases where we should abort the call.

**Comment by amcclain** [comment]
Re-routing to @TomTirapani as he's finishing up a round of autosizing wonders in #1877

**Comment by TomTirapani** [comment]
I don't believe this issue applies any more.

Our new autosizing does not depend upon the grid / columns / data being rendered to autosize according to its data. A grid in a background tab or otherwise hidden can still be autosized.

It's important to note that the current implementation *does* depend on the grid being rendered to autosize its *headers*, but if the headers are not available they will be quietly skipped and won't break the rest of the autosizing routine (i.e. worst case your header labels may clip).

**Comment by amcclain** [comment]
Agreed - we have a much improved story with Hoist autosize that will soon be promoted to the default.  Will close this ticket.
