### ISSUE TITLE
Select with async queryFn calls queryFn with empty string when refocused even if it has a value

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1847]

**Comment by lbwexler** [comment]
Hi @amcclain -- tried this with a couple of different options and unable to reproduce.  Can you give any more details, or paste in a copy of the elementFactory with its props? Thanks!

**Comment by cnrudd** [comment]
I'm not able to reproduce what I understand to be described,  but I do see an 'undefined' option showing up at the bottom of the options list.    I checked that the values returned by the queryFn do not include an 'undefined' value so this is something that might be added by the select component somehow.
![Screen-Recording-2020-09-23-at-1](https://user-images.githubusercontent.com/2573928/94031441-dc360d00-fd8c-11ea-8d1e-9bc50874edb9.gif)

**Comment by cnrudd** [comment]
A little more snooping reveals that the "undefined:undefined" box happens only when  there is an optionRenderer and "enableCreate:true".    The option renderer is not handling the "create one" entry well.   A different bug I think  than the one described in this ticket.

**Comment by cnrudd** [comment]
The issue I uncovered can be resolved by making some adjustments to the custom optionRenderer, as was done here:
https://github.com/xh/toolbox/commit/7c2e22e29b98409e2692601ce9841a1b4fee813f

I think's probably better to let a developer do that, if he is going to have both a renderOption and enableCreate:true on a select, rather than to try to code a defensive switch into the select component.  Here is a branch with such a switch:
https://github.com/xh/hoist-react/tree/selectEnableCreateWithOptionRenderer
The switch takes care of safely displaying the "Create XYZ" option in the dropdown menu, but it does not (cannot) handle the rendering of the option once it has been selected and re-appears in the dropdown menu.  The custom renderOption will have to take care of that.  So, there will always have to be some special logic in the custom renderOption to handle the created option if enableCreate: true.  Which brings the discussion back to the conclusion that it may be best to leave this usecase to be handled entirely by the developer.

**Comment by lbwexler** [comment]
which brings us back to the original ticket :-)

**Comment by amcclain** [comment]
Closing as neither of you saw this issue and it has not been a recurring report.
