### ISSUE TITLE
Record should have an isLeaf property

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1880]
When using a tree grid, sometimes you might want to, for example, only show a detail popup if the user has clicked on a leaf row, and not an aggregate row. One way to do this is to check if the record has any children. The wrinkle being, if you are using a Cube and you do not query for the leaves (includeLeaves: true) you can get a row that has no children but is still an aggregate (ie it's a leaf in the store but not in the cube).

Not sure how feasible this is but would be nice to have.

**Comment by lbwexler** [comment]
This is a bit tricky, because I think don means specifically here a "Cube" leaf, but not all records come from a cube, and the term leaf has perhaps different connotations on a Store Records.

(E.g. Just a record with no children, could be anywhere in the hierarchy, depending on source data, and filtering)

I discussed with him and the cleanest way to identify an actual cubeLeaf would be something like 
`data.cubeDimension == null`,  `cubeDimension` is a field  (like `cubeLabel`) that you can get for free on Store records created by the cube.
