### ISSUE TITLE
Checkbox focus affordance is clipped

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1885]
See Checkbox in toolbox FormModel and HoistInputs Tab.  Both of these show with the left side of the focus border missing

**Comment by febbraiod** [comment]
Also applies to switches and radio buttons. 

Oddly, this doesn't happen on window's machines. However, I think the bug is with windows, even though the bug makes the outline look better. 

It appears that the "outline-offset" css property is being ignored in Chrome on windows. The .bp3-control-indicator class has this property set to 2px, which is being respected in toolbox on Macs and causing the clip. Whereas in windows the outline hugs the outside of the input.

If we like the offset we'll need to give the inputs more room in toolbox. However we will not pick that up in windows due to the bug described above. Personally, I think the focus outlines should hug the inputs in the same way that they do for say a text input. That will be a css change in Hoist, but I have yet to determine where.
