### ISSUE TITLE
DimensionChooserModel should allow saving only the history

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1898]
Have a use-case where I need to share the dimension chooser history among multiple controls, but _not_ the value. Currently the built-in `preference` support in DimensionChooserModel saves both the value and history. 

Also would be ideal if the history changes could be synchronized between the different DimensionChooserModel instances. Perhaps this would require that we make prefs observable though?

Am not sure the best way to implement this, we could accept a spec for the `preference` config which could indicate which parts of the model state should be persisted to the pref. e.g. `{preference: {mode: 'historyOnly'}` - or we could just have a flag?

Alternatively we could just allow the app to take full control of the history by making it observable and providing a setter, and the ability to set the initial history (like we do for `initalDimensions`. That way the app could save and restore that history however it wanted and ignore the value

**Comment by febbraiod** [comment]
I like the idea of a new "historyOnly" flag, rather than changing and having to write code to parse the preference prop.

In a previous incarnation of our dimension chooser (hoist-sencha), the history preferences was checked and the history reset every time the chooser was shown. Now we only do this in the constructor. Is there any reason we can go back to the previous approach. Will con't to look into.

**Comment by lbwexler** [comment]
Don -- it occurred to me that the best option would be to change things so that we have **two** options to DimensionChooserModel

`historyPreference` and (existing) `preference` --  Where the former governed a place to put history, and the latter governed a place to put the value.  For backward compatibility `historyPreference` could default to `preference`, but they both could be set to anything, including null!   

Would give more flexibility when you actually did want to save both bits to preferences, but just wanted to share history. 

Also will go better in the future if we enhance "xxxPreference" to be some more generalized adaptor (a set of closures?) rather than just a string....

**Comment by febbraiod** [comment]
Sounds good
