### ISSUE TITLE
Mobile impersonation user select should allow user to enter a username

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1902]
Currently just a drop-down menu, so if a user has not yet logged into the system and is not in our list of users, there is no way to impersonate as them on mobile.

**Comment by febbraiod** [comment]
This is trickier than it appears on its face. Mobile select disallows type ahead (and creatableMode) due to concerns about the Mobile keyboard. IE unless your select is at the very top of the screen the keyboard might cover up the dropdown results. (Which in this case it is).

Spoke to Tom. He thinks we can add these props to the mobile select as long as they default to being off. Perhaps we can warn future devs with a comment.
