### ISSUE TITLE
Add persistWith support for TabContainerModel

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1980]
Would be nice to be able to easily persist the active tab with a one liner

**Comment by cnrudd** [comment]
Starting work on this now.

**Comment by cnrudd** [comment]
@lbwexler I've looked at TabModel.js and and TabContainerModel.js.    Do you really mean put a persistWith config on TabModel?   or do you mean put one on TabContainerModel?   My guess is you meant put persistWith on TabContainerModel so that it can persist which of its tabs is active, but just checking.

**Comment by lbwexler** [comment]
yep, thanks!
