### ISSUE TITLE
Enabling codeInput toolbar breaks sizing under certain circumstances

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2046]
I spent a lot of time trying to understand what's happening but could not.

CodeInput w/new toolbar feature enabled appears to behave OK in most cases, but in a dialog showing the toolbar causes toolbar to take up all available height.  I wanted to set `enableSearch: true` for the JSON REST-editor field and ran into this:

<img width="669" alt="Screen Shot 2020-08-27 at 8 25 27 AM" src="https://user-images.githubusercontent.com/225806/91441970-220bbe00-e83f-11ea-9ff5-902e8436608e.png">

Very frustrating to be honest - we have set these flex properties on the CodeMirror div but I don't really understand them, and I can't understand why the toolbar takes up all space. Even giving the toolbar a fixed height didn't help - the tbar took the height, but the editor was still collapsed. I can't figure out what I am missing or still (after all these years) not understanding about how flex is working.

**Comment by TomTirapani** [comment]
Fixed this issue and reconsidered CodeInput's use of flex in this PR: https://github.com/xh/hoist-react/pull/2060

Getting CodeMirror to fill the space available has always been a pain, since its scrolling behaviour does not play well with flexbox, so was good to revisit this. In particular, there were a lot of workarounds to get horizontal scrolling to work properly.

Hopefully the new approach in the PR is easier to understand. We no longer flex CodeMirror itself at all. Instead, the input contains a flexed wrapper element that fills up all available space, and then CodeMirror is absolutely positioned within that. It seems to work well across the various permutations (flexed / sized, inline, in a formfield / standalone, etc) without breaking the horizontal scrolling.

**Comment by amcclain** [comment]
Thanks very much for diving into this and resolving, Tom.  Appreciate it.

**Comment by amcclain** [comment]
Sorry to reopen, but found one issue where if you give the codeInput/jsonInput itself a height (to customize off of the default 100px) that height will be sticky when you open in full screen.

Here in the Toolbox "Hoist Inputs" tab I've modified the jsonInput row as follows:

```
                    row({
                        label: 'JSONInput',
                        field: 'text5',
                        // layout: {height: 200},
                        item: jsonInput({height: 250})
                    })
```

and get this result when opening fullscreen:

<img width="1545" alt="Screen Shot 2020-09-09 at 5 56 36 AM" src="https://user-images.githubusercontent.com/225806/92601302-80826480-f261-11ea-9a4f-14211d8fec5f.png">

I ran into this when attempting again to customize our RestForm defaults for jsonInput to make it a bit larger.  )The 100px height that remains as a default in CSS doesn't really work when a toolbar is visible.)

**Comment by TomTirapani** [comment]
Ah okay - thanks for catching. Will take another look

**Comment by TomTirapani** [comment]
Should be fixed now - I had left in some code where we were still sizing the CM instance directly. https://github.com/xh/hoist-react/commit/560da4230166955f59c9612c0aabb59ee9a40ab4

**Comment by amcclain** [comment]
Thank you! That fixed one or two other mysterious layout bugs I was seeing when attempting to customize the size in our RestForm dialog. Will keep an eye out for any other issues but looking much better now.

**Comment by lbwexler** [comment]
Take 2 -- thanks for the careful work here guys!
