### ISSUE TITLE
Support messageKey property to avoid dupe XH.alerts/confirms

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2105]
A process might call `XH.alert()` and related methods powered by `MessageSourceModel` multiple times and yet only want the last call to show, instead of stacking up multiple modal alerts and creating a storm of modals on the browser.

Our message APIs could take an optional property such as `messageKey` which, if provided, would auto-close any modals created with the same key before showing the latest request.

**Comment by lbwexler** [comment]
Here is an interesting commentary initiated by John.  Question is should we just hanging the promise?  rejecting it? or resolving it as cancel?  See discussion below:
if you are doing an await on the message promise it would never resolve right?

lee:maple_leaf:  8:21 AM
thought about that a bit, but not enough, obviously

john.haynes  8:21 AM
:slightly_smiling_face:

lee:maple_leaf:  8:21 AM
my thought was that user never answered the question, so we don’t want to resolve

john.haynes  8:21 AM
I think cancelling makes sense?
8:21
yeah its a tricky one
8:23
or does it make sense to reject the old promise?

lee:maple_leaf:  8:24 AM
thinking… conceptually that seems appealing

john.haynes  8:25 AM
yeah I think I like that more than calling cancel since we can't really assume that apps don't have special logic when cancelling

lee:maple_leaf:  8:25 AM
but that could also yield some errors in user code

john.haynes  8:26 AM
yeah

lee:maple_leaf:  8:27 AM
what would you want in your use case — was just an alert, right, where you did not care about the answer
New

john.haynes  8:27 AM
nope was a confirm
8:27
in my case cancelling would be fine because I don't do anything unless they confirm
8:28
but some uses of confirm could case more about the answer and do something either way

lee:maple_leaf:  8:30 AM
well we do have this precedent here —
// Message modals are automatically dismissed on app route changes to avoid navigating the
// app underneath the dialog in an unsettling way.
this.addReaction({
    track: () => XH.routerState,
    run: () => this.close()
});
8:34
but on the other hand, clicking escape, would cancel, and it seems close to that — also the word cancel, arguably implies the no-op action for the app
8:37
So cancelling would be good for an app that was asking “Discard Changes?” And not so good for an app that was asking “Save Changes?”
8:38
Perhaps the latter is a poorly written app, if it ties an active state change to a “cancel” operation….
