### ISSUE TITLE
Tab close button hover radius too small

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2158]
The Tab x-button is too bulky on hover -- seems okay in light mode on toolbox tabPanelContainerPanel dynamic model, but broken in dark mode. Tried using this from snapshot version in client app and is also bulky in light mode there.

**Comment by TomTirapani** [comment]
This is due to competing levels of styling specificity with our core button styles. In particular, these lines create a high level of specificity in the base rules that make them difficult to override:
https://github.com/xh/hoist-react/blob/develop/desktop/cmp/button/Button.scss#L12-L14

Here is a PR which resolves these competing styles using `!important`:
https://github.com/xh/hoist-react/pull/2160

Discussed with @amcclain , and we decided to circle back later and re-examine if the core button rules need to be so specific, but that changing the core styling is not warranted for this issue.
