### ISSUE TITLE
Summary row in grid not distinct enough with tree mode styles

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2163]
It would be nice to have a more distinct demarcation for the summary row in these tree mode styles, especially in this case where we already have row borders in the grid -- perhaps some additional color shading or stronger border?
![Screen Shot 2020-10-27 at 9 08 59 AM](https://user-images.githubusercontent.com/49966727/97306024-3e72a980-1834-11eb-9811-f530ce51b733.png)

**Comment by lbwexler** [comment]
Or to put it another way, when a grid is in tree mode, the total row should be styled like a group, which it conceptually is!

**Comment by febbraiod** [comment]
I thought we covered that. Definitely remember discussing it as the zeroth group. Must have regressed it on some iteration.

**Comment by febbraiod** [comment]
Looks like we did cover this, but in Petra's screenshot above you'll notice that highlights and borders is selected but NONE of the rows are highlighted. This is because there is only one dim selected. So I'm assuming that ag-grid is not using the group css classes in this case. If you go to a second level in the dim chooser you get what is expected:

<img width="1346" alt="Screen Shot 2020-10-29 at 2 35 40 PM" src="https://user-images.githubusercontent.com/15745614/97617662-6c065100-19f4-11eb-9c19-5edde960e504.png">
