### ISSUE TITLE
Grid rowStriping does not reset across grouping levels

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2191]
Our row striping styling keys off of ag-grid's `ag-row-odd` class, which is applied in a "flat" manner to grid rows, irrespective of nesting levels due to grouping.

In particular, this causes tree grids to be styled so that the first leaf row in a given group might sometimes have the base grid background and sometimes have the shaded alt bg.

This in turn can interact with treeStyling on parent rows to look pretty weird in derivative (but not super-rare) cases where you have groups of one child. Depending on the overall grouping level, you can have cases where sometimes that leaf child is shaded and sometimes not, and it's confusing.

Need to work out a better approach to shading with and without the tree styles, also taking into account non-tree grouping (full width and other custom ag). Would suggest we first try to reason that out / write it down so we have a spec, then see what an implementation would look like and if it's feasible enough to act on.

**Comment by febbraiod** [comment]
Petra and I (with a short consult with John H) took a look at a couple of approaches but all seem to be problematic in one way or another.

1) Purely CSS approach. Idea was that instead of using ag-grids even/odd classes we could identify the first leaf row in a group by targeting .ag-row class (without the group row class) as a child of a group row and use :nth-child(even). However, it appears that these row don't have a parent child relationship in the DOM

2) Con't to try to target the leaves specifically using rowClassFn in the JS to apply custom classes. Trouble here is when examining the row it is not easy (impossible?) to tell if the child is a proper leaf. IE A row might not have children but still be at a group row level, in which case we don't want to apply these custom leaf striping classes to it.

3) Use rowClassFn to stripe groups individually. It has been theorized that we can use the group's childIndex to reset striping under the deepest level parent node. I did not look closely at this so unsure how exactly that would work.

JH said there is some concern with 2 or 3 because if the data/shape changes it could cause the entire grid to need to be rerendered.
