### ISSUE TITLE
Support for variable height rows in Grid

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2196]
If a dataset has some data in a column that requires multiple lines, agGrid provides an affordance for that:
`column.autoHeight: true`.

In a HR grid column, this would be:
```
agOptions: {
  autoHeight: true
}
```

This column.autoHeight option is ignored by agGrid when a getRowHeight function is also provided to the grid.

In a HR grid, a getRowHeight function is ALWAYS provided to the grid because it is used to set the rowheight according to sizing mode.

Possible solutions:

1. Promote autoHeight to a top level column config property, and do not provide any getRowHeight function if a column has an autoHeight:true setting.  agGrid will calculate rowheights based on the content of that multi-line column.
2. Maintain current behavior, but when agOptions.autoHeight:true is attempted, provide a console warning explaining that Hoist-React grids are really intended for single line data. Developer should consider a DataView component instead of a grid.

AgGrid is doubling down on its `autoHeight` feature.  In v24 it introduces `textWrap:true` which it says should be used in conjunction with `autoHeight:true`.  

This issue was discovered while upgrading a client app that attempts to display multiline data in a column.
I can think of one other client app that already displays comments in a grid column (currently limited to one line and elided).
Developers might expect to be able to take advantage of the textWrap: true, autoHeight:true feature for these comments when they become available in v24.

In v23, `autoHeight:true` all by itself works best when the column's width is preset, not flexed.  On flexed columns the height is incorrectly calculated based on the minimum starting width of the column, not the final flexed width, so empty data needs to be preloaded before real data is called for and loaded, to get ag-Grid to correctly expand the target flex column.
This issue isn't obvious on this demo: https://plnkr.co/plunk/yCrRkXSuZphaA6gm, but can be seen in the client app.

But, in v24, `autoHeight:true` & `wordwrap:true` work very well on a flex column.  See: https://plnkr.co/plunk/N6C2bTo4OoHBjoDQ
and also in the client app, without any need for the above described empty preload workaround.

**Comment by cnrudd** [comment]
Here are branches in HR and Toolbox that demo a solution and its drawback:
https://github.com/xh/hoist-react/compare/agGridAutoHeight?expand=1
https://github.com/xh/toolbox/compare/agGridAutoHeight?expand=1

Drawback being that sizingMode applied to rowHeight must be ignored across whole grid when a column specifies `autoHeight: true`.   This is is not an issue if all rows have multiline content, but could be annoying if a minority of rows do.

We also might consider setting `agOptions.wrapText: true` on a column by default if it has `agOptions.autoHeight: true`.

**Comment by TomTirapani** [comment]
Hey guys, what's the status of this? This would be useful for a client-app we're currently porting, where we have a particular need for variable row height DataView.

**Comment by cnrudd** [comment]
@TomTirapani Hi Tim, I've updated the two branches mentioned above with the latest from develop, and created 2 PRs, to get the process started on reviewing this.

**Comment by TomTirapani** [comment]
Thanks for taking a look at this, and for taking the time to discuss the options yesterday.

### GridModel and AgGridModel
I'm not familiar with the client request that originated this ticket, but if we want support for `Grid` and `AgGrid` variable row height we can go with this PR: https://github.com/xh/hoist-react/pull/2283

This adds (unadvertised) support for using `Column.agOptions: {autoHeight: true, wrapText: true}}` to dynamically size rows based on their content, while respecting `GridModel.sizingMode`. Note that due to known AgGrid issues, this does not work with cells that use `elementRenderers` (the row height will fall back to the `sizingMode`).

### DataView
I think we should definitely go for this PR: https://github.com/xh/hoist-react/pull/2303, which adds support for an `DataViewModel.itemHeight` function. This is unrelated to the above PR, and can be taken separately.

We explored the idea of rendering DataView items to a hidden DOM wrapper to size them. While this proof of concept is promising, I would like to think more about the implementation and see how far the above PR takes us. If we do implement it, it may be worth extending our existing `ColumnWidthCalculator` to handle height-sizing as well, where we should be able to leverage the same performance considerations.

**Comment by lbwexler** [comment]
Changed the name to make this ticket more specific to Grid.  We have a (partial) solution merged now for DataView.  We could enhance with the POC described above in the future.

In any case, think the issues with Grid and DataView are sufficiently different that best not to conflate these to in a single ticket.
