### ISSUE TITLE
ButtonGroup borders / margin off in dark mode

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2199]
Another tricky issue - likely with CSS specificity - with buttons and dark mode. In this case outlined buttons within a `ButtonGroup` (note _not_ `ButtonGroupInput`) lose their cohesiveness when in dark mode:

Light mode (OK):
<img width="508" alt="Screen Shot 2020-11-23 at 2 48 21 PM" src="https://user-images.githubusercontent.com/225806/100024263-496d1b00-2d9b-11eb-99fb-906c69cc6a2e.png">

Dark mode (problem):
<img width="610" alt="Screen Shot 2020-11-23 at 2 48 12 PM" src="https://user-images.githubusercontent.com/225806/100024267-4b36de80-2d9b-11eb-896e-28ad671c4e40.png">

**Comment by TomTirapani** [comment]
The actual cause of this is more straightforward... we were using the blueprint ButtonGroup directly in these views, rather than our own wrapped component! Have confirmed that the dark theme borders / margin are more consistent when using our own component.

https://github.com/xh/hoist-react/pull/2588
