### ISSUE TITLE
TreeStyle.BORDERS does not apply to top-level rows without children

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2201]
Looks like the css will only apply if the row has children, which looks a bit off in grids where the root parent rows may not all have children. I think we should just make the borders apply to all of the top-level rows in tree grids (except the first row)

**Comment by amcclain** [comment]
I _think_ the same should be true of the background shading, if enabled. In another app use-case, I found it a bit jarring that this top-level group row is styled more like a child row (because it does not itself have any children):

<img width="305" alt="Screen Shot 2020-11-24 at 12 32 12 PM" src="https://user-images.githubusercontent.com/225806/100148172-39b00e00-2e51-11eb-865a-e3272aade271.png">

**Comment by febbraiod** [comment]
Seems logical that I should have a look at this after having worked on the tree styles originally and in light of recent research on https://github.com/xh/hoist-react/issues/2191.

**Comment by amcclain** [comment]
Thanks, Don!
