### ISSUE TITLE
Support "force reload" option from Admin > General > Websockets

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2216]
For websocket connected users / browsers, we should be able to leverage the socket connection to prompt a connected app to reload itself in the browser. This can be useful for rare-but-real cases where we want to ensure a user refreshes, e.g. to pick up a new set of configs or preferences or clear some other client-side error we have reason to believe exists.

**Comment by lbwexler** [comment]
This came up at a client, where we changed some client configs and really wanted to pick them up.   
+1 for this important feature.  

HOWEVER -- Please keep in mind that using sockets for this core feature will make it harder for us to go multi-instance.

**Comment by lbwexler** [comment]
I was thinking that we might be better off using the '/version` endpoint timer based pull  we have in place for a broader set of applications.  It already is in the business of getting the client to refresh when needed due to a version upgrade.  We could rename it to something like 'environmentCheck' or `clientPing`, but we could also leave the name as is, as it is a form of version checking.

Cons: It might be slightly slower to force the refresh, and would not allow us to easily target individual users.
Pros:  It could be broader, and would work multiple-instance as well.

A simple implementation right now would be to add a date (in memory) on the server of "refreshRequired", which had the latest date, if any, that a refresh was required.

The timer in environmentService could consult this data, and if any client was loaded after the date of `refreshRequired`, it would need to be reloaded.

**Comment by lbwexler** [comment]
Adding this ticket for Dan -- seemed like it might be an interesting one for you Dan.

**Comment by amcclain** [comment]
Discussed further with @lbwexler, and we determined that it would still be worth it to implement this feature as originally spec'd. There can be some cases where targeting a particular user is helpful, and the current websocket services are already setup nicely to handle this.

We also discussed a potential force-reload enhancement to the version checking routine that would _not_ rely on websockets and could cover many of the cases where we want to ensure clients refresh ASAP after a release. Will ticket that in a separate issue.
