### ISSUE TITLE
AG-grid 25 support

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2254]
Specifically, in toolbox, the tree grid with checkboxes: clicking on a checkbox causes the entire column to flash. Data updates cause the same. We think something may have changed with the agApi.refreshCells() method.

**Comment by lbwexler** [comment]
**So I went down this particular rabbit hole this AM. Some points:**

+ It looks like ag-Grid is now remounting React components much more aggressively when a change is detected in the row or it is force refreshed.  Not sure if it is a bug, but certainly a change.  The refresh() framework method on our wrapping react component seems to be called less often.  This is causing the flashing
+ The checkbox renderer in the example Don mentions is a `isComplexRenderer` *and* an `elementRenderer`.  That is the bad combination for this new ag behavior, because it will cause a react remounting of all cells whenever any cell is edited.

**I think we should consider the following**

[a] Contacting ag-Grid, and making sure this is not a bug.

[b] If we can fully commit to using ag transactions (which we should -- we have had the experimental flag default on for many releases) then we can also be a little more selective on the `forceUpdate` that we are doing on columns with `isComplexRenderer`.  I think we should probably just do this and will put it in a PR.

[c] We should consider implementing the `refresh()` method on our wrapping framework component (which can now be either a function or a class)   

[d]  A somewhat related thought to [b].  Intsead of the using the `forceUpdate()` approach we currently use for `isComplexRenderer`, we could have columns like this use the entire `record` as their default value, so that ag-Grid can use its native change management on the column.  This would require a little work on our part to get the sorting right, and might be a bit more confusing for developers, but ultimately might be more harmonious with the ag-Grid change management.  It might be too late to switch to this method for our implementation of `isComplexRenderer`, but thought worth mentioning.  It seems to work in my experimentation.

**Comment by lbwexler** [comment]
NOTE:  Just discovered an issue with our absolute value sort regressing.  Also seeing a little (new) flicker in our group header rendering that may be a clue regarding the issue with the checkbox rendering!?

**Comment by lbwexler** [comment]
I don't think the flickering with the element rendering is a show stopper at this point.  curious to hear other people's opinions.
