### ISSUE TITLE
Mask improvements: Better defaulting, and less expensive masking on VMs

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2330]
With many users accessing our apps over VPN connections, some report that any animation causes latency on their VM.

Our Mask with animated spinner can be a source/cause of latency.

When used in a [Panel](https://github.com/xh/hoist-react/blob/05129c757f74e26bf5365bec2c2340bd49fa87f2/desktop/cmp/panel/Panel.js#L148), our Mask component by default shows an animated spinner.  To not show the spinner on any mask in an app requires configuring every Panel with a customized Mask component.

This is a bit of a chore, and it might be worth finding an app wide way to configure the appearance of all Masks.

Also, it would be nice to easily show an icon or image that isn't animated, rather than no icon/image at all.

**Comment by pauldelano** [comment]
I have an app that periodically locks up the VDI (beachball on Mac) while the spinner is displayed. It seems to have something to do with the state of the VDI, VPN or network connection since it is not always so intrusive.

I have also run into a case where the app permanently locked up when multiple spinners were shown at the same time.

It has become enough of an issue so I have added a preference to turn off spinners when necessary. That is not a desirable solution since the interface does look much better if there is a work-in-progress indicator on the screen.

**Comment by amcclain** [comment]
I am looking at this.

**Comment by lbwexler** [comment]
Closing this, as we currently think that the new spinner component addresses the main reason behind this ticket.

We can always revisit the idea of improving our mask API, which is more of an open-ended problem.
