### ISSUE TITLE
Collapsed Vertical Panel Title not aligned properly

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2335]
See toolbox example attached.  also seeing this on a client app.

Is this a regression?  Is it intentional and I am seeing it wrong?  
<img width="323" alt="Screen Shot 2021-03-09 at 6 10 00 PM" src="https://user-images.githubusercontent.com/2307561/110551201-1ad53f00-8103-11eb-96f2-30d2e65d144d.png">

Seems to me that this needs to be center aligned.

**Comment by febbraiod** [comment]
Appears to be a bug/change in Chrome 89. Chrome 88 does not present this issue.

**Comment by febbraiod** [comment]
Can't seem to find any known issues to this effect. Observations:

1) The width the title element is 20px when inspected in Chrome 88. 30px when viewed in Chrome 89. The alignment is probably off because it's based on this difference in size. What changed about flex child sizing?

If manually set to 20px width the title is in the right place.

2) Tom notes that changing the line height to 2em fixes the issue as well.

**Comment by lbwexler** [comment]
Well this seems suspicious, with respect to those 10px Don is looking to clawback:

 &.xh-panel-header--right {
      & > .svg-inline--fa {
        margin: 0 0 10px 0;
      }
    }

I am fine with a work-around based on either of the two approaches mentioned above.  We can't ignore this one, unfortunately.

**Comment by febbraiod** [comment]
The "margin: 0 0 10px 0;" pixels are in the wrong direction for our issue. 10px bottom is the separation between the glyph and the title.

Tom and I agreed setting the width is the thing to do.
