### ISSUE TITLE
Update Golden Layout to v2.x

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2345]
https://github.com/golden-layout/golden-layout/releases

**Comment by lbwexler** [comment]
Closing this, as this particular ticket not an actionable  option for us right now, due to Golden Layout dropping support for React v 2.0.

When we revisit, we could consider one of these react based options
 
+ https://github.com/annotationhub/react-golden-layout. or this:
+ https://github.com/caplin/FlexLayout
