### ISSUE TITLE
select component should set class from className

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#2416]
This appears to be a regression somewhere between 36.6.1 and 40.0.0.

**Comment by amcclain** [comment]
I might be misunderstanding this bug report, but I am seeing a `className` prop supplied to a desktop `select` component getting passed through as intended to the rendered div. Here I have added a `tb-select1` class to the Toolbox inputs example in my local sandbox, running with the latest Hoist snapshot:

<img width="514" alt="Screen Shot 2021-05-04 at 6 17 23 AM" src="https://user-images.githubusercontent.com/225806/117009386-891c2500-aca0-11eb-9ad0-6d78d3299edf.png">

and I can see it OK in the rendered markup:

<img width="983" alt="Screen Shot 2021-05-04 at 6 16 51 AM" src="https://user-images.githubusercontent.com/225806/117009545-bbc61d80-aca0-11eb-8960-1fe59182bf5c.png">

Looking at the diff from v40.0.0 to now, I don't see any indication this has changed since release. Let me know if I'm missing it? Thanks.

**Comment by lbwexler** [comment]
Yes, in 36.6.1, the class is place on the div in the same way.

It is true that we aren't 100% consistent with where we place the class in our HoistInput implementations.  Sometimes we pass it through to the underlying Blueprint (and presumably HTML element), and sometimes we put it on a div.   For example, in `NumberInput` we do the former and `TextInput` we do the latter.

**Comment by pauldelano** [comment]
Yes, select does pass through className properly. This can be closed.
I was mistakenly overriding the className when creating my select().
Thanks for following up promptly!
