### ISSUE TITLE
Adjust mask colors to better blend with theme background

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2690]
This is especially important when only masking a single widget, or detail panel on a page.  (e.g. Dashboards)   The gray really stands out more than it needs to.

See our masking in legacy client sencha apps for example of the benefits of this.

**Comment by amcclain** [comment]
Spent a while looking at this - I think that we have real room to improve here and that any improvement will make a noticeable difference across apps. It is more complicated than it appears, though - of course...

- There is a difference between masks used as "backdrops" behind dialogs and alerts vs. "overlays" that appear on top of grids and other components.

- An update to use the overall (white/black) background color works especially well for overlays - that is what prompted this ticket.
  - Proposed (below) has a light touch with the combination of the app-color bg at 40% opacity. It's a bit difficult to see in screenshots, but it is noticeable. Could be more opaque, but I think keeping it relatively low is part of the idea.
  - Mask text background looks off if not also changed - one option (pictured) would be to give it the solid background color + border to set it apart.

**Current:**
<img width="1318" alt="Screen Shot 2021-09-27 at 1 34 54 PM" src="https://user-images.githubusercontent.com/225806/134981201-903ee6a6-4ce2-4f36-a673-b5aad7bb9c01.png">
<img width="1318" alt="Screen Shot 2021-09-27 at 1 36 00 PM" src="https://user-images.githubusercontent.com/225806/134981374-7cc64af2-e5dc-4949-8bfd-faee90f4510d.png">

**Proposed @ 40% opacity**
<img width="1318" alt="Screen Shot 2021-09-27 at 1 35 04 PM" src="https://user-images.githubusercontent.com/225806/134981236-065ce75b-3c28-41dd-bdae-ae5d866388bb.png">
<img width="1318" alt="Screen Shot 2021-09-27 at 1 36 10 PM" src="https://user-images.githubusercontent.com/225806/134981488-cd1360e6-f1fe-48a6-82aa-77aaa301fec8.png">


When looking @ this on desktop, however, I realized that our current *backdrop* masking is actually layering on two "masks" due to how we were trying to use our CSS var.  A modal blueprint dialog renders two divs - `bp3-overlay-backdrop` which is currently retaining a bg-color from BP styles as well as `bp3-dialog-container` which we style with our mask background.

**Current:**
<img width="1318" alt="Screen Shot 2021-09-27 at 1 50 45 PM" src="https://user-images.githubusercontent.com/225806/134983409-38b2a70b-78c3-4927-9994-1bd23e72a31e.png">
<img width="1318" alt="Screen Shot 2021-09-27 at 1 51 37 PM" src="https://user-images.githubusercontent.com/225806/134983418-14f7b251-b26f-4853-9023-9d34b3ef9409.png">

If we remove the double-masking so we can adjust/test with just our color, using the same lighter-weight (40%) mask for the backdrop does not seem like it is enough for backdrops:

**Proposed (but not really) @ 40% opacity**
<img width="1274" alt="Screen Shot 2021-09-27 at 1 53 24 PM" src="https://user-images.githubusercontent.com/225806/134983723-444375c4-3126-4cbe-899c-76989969ba1e.png">
<img width="1318" alt="Screen Shot 2021-09-27 at 1 53 56 PM" src="https://user-images.githubusercontent.com/225806/134983786-1ac42fa0-f411-45e7-8cb5-462d7fb61fa5.png">

Even more so on mobile, where the dialog and the components below it can end up pretty jumbled:

**Proposed (but not really) @ 40% opacity**
<img width="569" alt="Screen Shot 2021-09-27 at 1 55 30 PM" src="https://user-images.githubusercontent.com/225806/134983984-297d02b0-2dc6-4f17-b3b0-0daec0198a3c.png">

**Comment by amcclain** [comment]
The mobile dialogs still didn't look great to me, but there I found that we were doing much better if we removed mobile-specific overrides to --xh-title-* vars.  I am not sure why we have those in there - using the same values as we do for desktop + a 2px margin improves the situation to my eyes:

<img width="612" alt="Screen Shot 2021-09-27 at 2 42 20 PM" src="https://user-images.githubusercontent.com/225806/134989493-976cfb98-eaf9-414d-843a-dc83b97fef3c.png">
<img width="612" alt="Screen Shot 2021-09-27 at 2 42 28 PM" src="https://user-images.githubusercontent.com/225806/134989498-0b30bf2a-e432-4a2f-9cc8-d60d4c4af31d.png">

**Comment by amcclain** [comment]
Mobile dialog changes re. title / border colors pushed directly to develop @ aaf7b5a66ebfcdd50bbf9068365e8a9dcd84ef94
