### ISSUE TITLE
filterable 'id' field breaks grid defaultContextMenu

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#2724]
In a `GridModel`, if you make the `id` column `filterable`, it breaks the `filter` option in the `GridModel.defaultContextMenu`. Seems it’s because the `GridFilterModel.fieldSpecs` don’t include `id` because `Store.fieldNames` doesn’t include `id`. See `GridFilterModel.parseFieldSpecs()`.

**Comment by TomTirapani** [comment]
Thanks for catching and filing Paul. Please see the following PR, which ensures the menu checks both if the column is filterable and that the filtermodel has an underlying fieldSpec: https://github.com/xh/hoist-react/pull/2727

However @pauldelano, even if you manually include 'id' in your `fieldSpec`, filtering by `id` is generally not supported and such filters will be a no-op. This is due to `id` not being a field on the record, and our Store & Filtering systems have a strong notion of only supporting filtering by record fields. I'll discuss with Anselm and Lee the pros, cons and complexity of supporting filtering by id but, for now, you may be able to hoist the id into a pseudofield and filter by that instead?
