### ISSUE TITLE
Certain string type cell values get coerced to doubles in Excel export

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2757]
Client reported this issue where certain string values like:
"12345D" or "12345F" or "12345E1" might get coerced to a double since those suffixes are valid when it reaches our line of code in hoist-core:
https://github.com/xh/hoist-core/blob/4fb12aecc1b87d9b3558542015c860b97be3314f/grails-app/services/io/xh/hoist/export/GridExportImplService.groovy#L213

We could assign a metadata.type here to avoid the unexpected accident above:
https://github.com/xh/hoist-react/blob/fb4e48e8e0c65dda8da126d9e89ae3267be46466/svc/GridExportService.js#L181

**Comment by lbwexler** [comment]
Jakub -- please be sure to speak with Petra on this -- she has a lot of expertise on exports

**Comment by jskupsik** [comment]
I know this ticket is about the 'number' constructs which we have more-or-less figured out to always default to strings when unsure, but while trying to switch to using our new type values I noticed we are here I noticed we are doing very strange things with dates and datetimes.

Current code, illustrates the issue:
https://github.com/xh/hoist-core/blob/605466a7743e6ce3204f44bd839e3f7bd78bb19a/grails-app/services/io/xh/hoist/export/GridExportImplService.groovy#L218

I took a closer look at this and realized that the current export function appears to assume that our two date ExcelFormat (DATE_FMT or DATETIME_FMT) are stored as strings. This is different from our FieldTypes DATE and LOCAL_DATE as well as from Excel itself, all of which represent dates as a number in Unix time. For example, according to this code, the current expected value of an ExcelFormat = DATE_FMT field is the string `"2022-05-06"` (which the linked code turns into a Date object which is then converted into a Unix time number by the setCellValue utility), rather than just the numeric value like `1651795200` which is what a LOCAL_DATE would store.

If we encounter a FieldType of DATE or LOCAL_DATE it is very simple to export it to excel as the value is already in the correct Unix time and we can default the excel format to render this cell as a date (or use a custom ExcelFormat, if provided).

BUT if we encounter one of these legacy values (do they exist?), a FieldType of AUTO (set because it was not defined) with an ExcelFormat of DATE_FMT or DATETIME_FMT, should we continue to export it as a string-formatted date? Should we attempt to check if it's a string-formatted date or a unix number date? Or should we just print it as a string as written. Writing `"2022-05-06"` to an excel file rather than a date doesn't seem that harmful as the user can just press enter to get excel to convert the value for them.
