### ISSUE TITLE
Improve discoverability of FilterChooser fields

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2802]
It would be nice if the filter field list/info was available somehow without needing to type anything into the filter chooser, especially for cases where the chooser is not directly tied to columns in a grid. Have been asked multiple times over the last few months to remind (non-business) users which fields are supported.

One option would be to display all of the example options as default options when you focus onto the FilterChooser. This may further complicate the already complicated implementation though.

Another option may be to build a help popup which displays the same example options in a list for reference. This could be tied to a separate component that apps could display next to the filter chooser (a ? icon with a popover) or elsewhere in the app if they wanted to. Might also consider adding some description/additional text to be displayed to describe the fields if the display name is not sufficient.

**Comment by amcclain** [comment]
Hi - I like this suggestion, as I've had similar usability concerns and think that many users might not realize / be able to use the full power of the component. Would love to brainstorm more on this.

**Comment by amcclain** [comment]
Would like to discuss this when we have a chance / let us know if this has come up again. We can up the priority or look for incremental wins.

**Comment by TomTirapani** [comment]
I'm also interested in this one, and happy to take it on. Available to discuss options any time.

**Comment by TomTirapani** [comment]
I took a pass at determining the feasibility of the first suggested solution (showing the list fields before typing a query), and it turned out to be easier and less invasive that I expected. Was able to implement with minimal code changes and no breaking changes here:

https://github.com/xh/hoist-react/pull/2829

I know we wanted to brainstorm solutions, and am still open to different approaches - just thought I might as well open the PR for discussion since it was relatively low hanging fruit.

**Comment by lbwexler** [comment]
thanks tom -- all about the low-hanging fruit. 🍌
