### ISSUE TITLE
Admin Activity chart pop-out dialog does not display on first render

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2924]

**Comment by lbwexler** [comment]
So this results from "reusing" the same chartmodel to show the chart in two places.  Clever, and you can see why an application developer would want to do that, but chart model is not really prepared to do that, because it stores a reference to its actual high charts model in state.  

We are a bit inconsistent throughout the API about our expectations regarding whether multiple component 

You could certainly imagine a different implementation of chart/chart model that stored the highcharts object in a local component specific model but right now the object is on the main app model, and indeed documented as a public property which applications can read from.

**Comment by lbwexler** [comment]
Greg -- took an initial look at this and have some ideas.  Let's discuss

**Comment by ghsolomon** [comment]
Closed with #3019
