### ISSUE TITLE
Model lookup from context should also check JS getters that may return models

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2931]

**Comment by lbwexler** [comment]
Thanks for filing this Don.  It turns out this is a bit tricky.  

One thing that this revealed is a more subtle surprise -- we actually don't look up the class hierarchy when doing this lookup.  That's probably been fine in practice, because our HoistModel hierarchy's are rarely deep in practice.  But surprising nonetheless.

**Comment by lbwexler** [comment]
OK -- so I spent some more time on this and I think although we could change the code to call these, it is inadvisable to do so:

+ calling all unknown getters could be expensive and more importantly have unwanted side-effects, depending on how app models have been defined.  Especially problematic would be calling some getter during model lookup that would actually create a mobx dependency that we don't intend.

+ Good news -- the work to examine this allowed me to cleanup some of our model lookup code and perhaps make it more efficient.  See https://github.com/xh/hoist-react/pull/2983
