### ISSUE TITLE
Inline selectEditor can no longer be used to null out value

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3005]
Observed in client app. Previously the user could delete the existing value, tab out of the cell and have it remain blank. Now the previous value remains in the grid.

**Comment by lbwexler** [comment]
yes, seeing this now

**Comment by lbwexler** [comment]
Discussed this with Don.  This does *not* appear to be a regression with our select cell editor, which never allows you to null out a value, unless you provide `enableClear` true as an option, in which case it works.

Rather, the client app in question had a custom cell editor whose behavior seems to have changed due to the ag-Grid upgrade.

Leaving this open as the behavior of our SelectEditor (and indeed select itself) seems pretty sub-optimal.  Indeed -- why are you not able to clear the value by deleting all of the text?

Will have Don show me the custom editor in question.

**Comment by amcclain** [comment]
I'd suggest we close this one, unless we still think this is an issue.  If I understand correctly, our enableClear flag provides the required functionality (nulling out an existing value).

I know what you mean re. current behavior, but IMO deleting all the text is a bit ambiguous. The editable text is really used for filtering available options - you must actually choose an option to then select it (although tab selects the first option). So having deleted all the text, did you mean to set a null value, or did you just erase your query and then decide to move on before typing another one?

We could look at a change where deleting all the text offered a "Clear value" option above or below all the other options that, when selected like any other option, sets the value to null.  🤷

**Comment by lbwexler** [comment]
I agree we can close it -- our select is now aligned with the ag-Grid behavior, and its not something we have had a lot of complaints about.

Workaround will almost certainly be tricky, and it seems like the a can of worms we don't need to open!
