### ISSUE TITLE
Provide option to serialize grid state for visible columns only

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3046]
We have a client app that contains a large set of fields - 200+ - for a core business object.  We are creating dashboards with grid widgets that have all of these fields as available columns.  When looking at the saved state, a huge amount of the JSON that's persisted is tracking hidden cols, since these widget grids are expected to often show only a small subset of the available col set.

I don't recall why we serialize hidden cols to grid state, but my guess is that it relates to a best-faith effort to remember user sizing and ordering for hidden cols - i.e. hide then show a col, it's nice if it remembers where it was and how wide it was before you hid it the first time. (There might well be other, more important reasons, I have not reviewed.)

In this use case with a very large colSet, it would be a better tradeoff overall to only save viz cols, even if that meant a slight loss in functionalty.

**Comment by TomTirapani** [comment]
I *think* the reason we serialize hidden columns is to help us distinguish hidden from "new" columns, added in the code since you last saved state. If we make the default behaviour to only save state for visible columns, is the assumption that any column we don't have state for should be hidden?

**Comment by amcclain** [comment]
@lbwexler any thoughts on Tom's comment above?  

I don't have an opinion as to the importance of causing newly-added-visible-by-default columns to be shown automatically. I don't know how important it is.

**Comment by jskupsik** [comment]
I confirmed that adding a brand new column to a persisted grid will have it obtain default behavior of that column, which includes having it show up as visible.

In my experience, persisted grid layouts tend to either stay exactly the same or get completely outdated in cases where we are changing the fields/columns. I would support making this the default behavior as users have to click Restore Grid Defaults to view grid updates in most cases anyways.

**Comment by TomTirapani** [comment]
That's exactly my point... in situations where the grid becomes outdated, the user currently **doesn't** have to click "Restore Grid Defaults", since the columns/fields that don't have saved state are handled "as-is". In this new world, they would have to be assumed to be hidden, and the user would see an empty grid. And I'm sure we'll get more "bug" reports than users remembering to "Restore Grid Defaults" :)

Maybe that's okay - grids change a lot during development, but are generally pretty stable after a prod release - just wanted to make sure we are aware.

**Comment by lbwexler** [comment]
We could add a timestamp in code for when column was added, or changed, such that it should reappear to the user as a new column, and become unhidden, if it was greater than the last time the user saved grid state.   Would default to null.

**Comment by amcclain** [comment]
Doesn't seem like there's any straightforward path here, closing.

**Comment by lbwexler** [comment]
I actually thought my suggestion was not going to be *overly* complex -- we can discuss at next triage.

**Comment by jskupsik** [comment]
Looking over the code, there are 2 options that make sense to me.
1.) Make the serialized grid state only include visible columns
2.) Make the serialized grid state only include columns that differ from the default

The second option is easier to program, but I do not like how unpredictable it makes users' saved views if we chose to edit the default grid. In general, we seem to tend to keep user views the same rather than updating them/keeping them valid, so the first option sounds the best. For nearly every column schema update other than "adding a new column which is visible by default" (the only other case I am aware of is deleting a column entirely), the user's saved view does not change. We could even go as far as to consider the fact it does change in this one case a bug rather than a feature if we so desired.
