### ISSUE TITLE
Desktop DateInput clears when picking same date twice

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#3508]
If you use the calendar to pick the same date as the already selected value, it has the unexpected side-effect of clearing the value. 

Easily reproducible here:
https://toolbox.xh.io/app/forms/form

**Comment by TomTirapani** [comment]
Turns out this is the intended behaviour of Blueprint's DatePicker :/

It can be disabled quite easily by passing `canClearSelection: false` - however, this has the unfortunately side-effect of **also** disabling the 'Clear' button in the action bar. Not the end of the world, we have `enableClear` to add our own clear affordance, but makes the action bar look broken:

![Screenshot 2023-10-24 at 09 11 23](https://github.com/xh/hoist-react/assets/3017757/07840a8d-3c1c-4ffd-b4fa-c3342ea3a7bd)

Does anybody else find this default behaviour problematic? Does anybody actually use the action bar?

**Comment by amcclain** [comment]
Action bar used for convenience selection of "Today". 

Agreed, unfortunate that they disable that option rather than hide it completely.  

Not sure there's much to do here - at least it's good to know that there's some logic behind how the picker works. Anything else you think we shoudl follow up on, or good to close?

**Comment by TomTirapani** [comment]
I think we can close this, and keep it in mind if it becomes an issue in the future. I was able to work around it in the particular use case that prompted this issue by simply preventing null in the setter.
