### ISSUE TITLE
Tab Activation Hooks

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#459]
To bring TabContainer in line with framework routing libraries and to generally reduce the amount of wiring it takes to use routing it would be nice to have some hooks in place to help streamline the process of setting up routable components.

`onActivate(params)`
* Would eliminate the need for each Tab's content component to react to router state changes, check if they are the active route, etc.
* Would make sense to allow passing params to a Tab even if not using routing

`onDeactivate`
* Would not be as commonly used as `onActivate` but would allow a hook for a Tab to suspend some process if needed

`canActivate(params)`
* Most commonly used to reject a route if the user does not have necessary permissions, etc.
* Can return a boolean or Promise

`canDeactivate`
* Most commonly used if the current tab has unsaved changes which would potentially be lost if the user navigates away
* Can return a boolean or Promise

See https://router5.js.org/advanced/preventing-navigation for how to implement `canActivate` and `canDeactivate` with router5.

Also for reference see https://aurelia.io/docs/fundamentals/cheat-sheet#routing for details on how these same hooks work in the Aurelia router.

**Comment by lbwexler** [comment]
This looks like a fantastic ticket.  In theory, you could imagine building it deeper into the framework, but I am hoping that building it into TabContainer will be a sweet spot for adding the most useful functionality with minimal complexity.

Very curious to know how you might be able to support parts of this lifecycle even in the case of a non-route enabled tab container.

Also --  assuming these hooks would be looked for on the Contents of the Tab, rather than the TabModel?

**Comment by amcclain** [comment]
@haynesjm42 here is another candidate for Hoist work next week.
